[package]
name = "rsweeper"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2", features = ["full"] }
num-traits = "0.2.19"
piston_window = "0.132.0"
rand = "0.9.0"
text_io = "0.1.13"
